name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Toolchain
        run: rustup target add wasm32-wasip1
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
